config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    unauthenticated :user do
      root to: 'devise/registrations#new'
    end

    authenticated :user do
      root to: 'dashboards#current', as: :authenticated_root
    end
  end

  resources :users, only: :none do
    member do
      resources :payment_methods, except: [:index, :show],
        path: 'wallet', param: :payment_method_id
      resources :categories, except: [:index, :show], param: :category_id

      get '/profile', to: 'profiles#show'
    end
  end

  namespace :dashboards do
    get :current
    get :trends
  end

  resources :transactions do
    collection do
      post '/filter', to: 'transactions#filter'
      resources :imports, only: [:new, :create]
    end
  end
end

app/models/import.rb
class Import < ApplicationRecord
  has_many :transactions
  has_one :payment_method

  belongs_to :user

  validates_uniqueness_of :filename

  accepts_nested_attributes_for :transactions
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def new
    @import = Import.new
  end

  def create
    @import = Imports::CreateService.new(current_user,
                                         import_params).execute

    if @import.persisted?
      flash[:success] = "Transactions imported!"
      redirect_to transactions_path
    else
      flash[:danger] = "Something went wrong! Please try again!"
      render :new
    end
  end

  private

  def import_params
    params.permit(import_params_attributes)
  end

  def import_params_attributes
    [
      :file,
      :payment_method
    ]
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/_form.html.haml
= form_tag imports_path, method: :post, authenticity_token: true, multipart: true  do
  = label_tag "Payment Method"
  = select_tag :payment_method,
    options_from_collection_for_select(current_user.payment_methods, :id, :name)
  = file_field_tag :file, accept: 'text/csv'
  = submit_tag "Import"

app/views/imports/new.html.haml
%h2.bold.text-center Import CSV

- if flash.any?
  = render 'layouts/flashes'

.col-md-2.col-md-offset-5
  = render 'form'