config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    unauthenticated :user do
      root to: 'devise/registrations#new'
    end

    authenticated :user do
      root to: 'dashboards#current', as: :authenticated_root
    end
  end

  resources :users, only: :none do
    member do
      resources :payment_methods, except: [:index, :show],
        path: 'wallet', param: :payment_method_id
      resources :categories, except: [:index, :show], param: :category_id

      get '/profile', to: 'profiles#show'
    end
  end

  namespace :dashboards do
    get :current
    get :trends
  end

  resources :transactions do
    collection do
      post '/filter', to: 'transactions#filter'
      resources :imports, only: [:new, :create]
    end
  end
end

app/views/pages/_navbar.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar-main"}, aria: {expanded: "false"}}
        %span.sr-only Toggle navigation
        - 3.times do
          %span.icon-bar

      = link_to "$expensa", root_path, class: "navbar-brand"

    .collapse.navbar-collapse{id: "navbar-main"}
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= navbar_link_to current_user.total_balance, ""
            %li.dropdown
              %a.dropdown-toggle{href: "#", role: "button", data: {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"}}
                = fa_icon("plus")
              %ul.dropdown-menu
                %li= link_to "New Transaction", new_transaction_path
                %li.divider{role: "separator"}
                %li= link_to "New Category", new_category_path(current_user)
                %li= link_to "New Payment Method", new_payment_method_path(current_user)
            %li.dropdown
              %a.nav-item.dropdown-toggle{href: "#", role: "button", data: {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"}}
                = current_user.email
                %span.caret
              %ul.dropdown-menu
                %li= link_to "View Transactions", transactions_path
                %li.divider{role: "separator"}
                %li= link_to "Account", profile_user_path(current_user)
                %li.divider{role: "separator"}
                %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Log In", user_session_path

app/views/pages/_sub_navbar.html.haml
.col-md-12.sub-navbar
  %span.col-md-1.col-md-offset-5
    = navbar_link_to "Current", dashboards_current_path
  %span.col-md-1
    = navbar_link_to "Trends", dashboards_trends_path