config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    unauthenticated :user do
      root to: 'devise/registrations#new'
    end

    authenticated :user do
      root to: 'dashboards#current', as: :authenticated_root
    end
  end

  resources :users, only: :none do
    member do
      resources :payment_methods, except: [:index, :show],
        path: 'wallet', param: :payment_method_id
      resources :categories, except: [:index, :show], param: :category_id

      get '/profile', to: 'profiles#show'
    end
  end

  namespace :dashboards do
    get :current
    get :trends
  end

  resources :transactions do
    collection do
      post '/filter', to: 'transactions#filter'
      resources :imports, only: [:new, :create]
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include DatetimeSanitizer

  before_action :authenticate_user!
  before_action :set_transactions, except: [:new]

  before_action :set_month_year_label, only: [:index]

  before_action :find_transaction, except: [:new, :create, :index]

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transactions::CreateService.new(current_user,
                                                   transaction_params).execute

    if @transaction.saved?
      if params.dig(:transaction, :create_another) == "1"
        redirect_to new_transaction_path
      else
        redirect_to transactions_path
      end
    else
      render :new
    end
  end

  def index
    _transactions = current_user.transactions.filter_by_params(index_params).
      includes(:payment_method, :category).desc

    @transactions = Kaminari.paginate_array(_transactions).page(params[:page])
    @monthly_expenses = _transactions.total_expense
    @monthly_income = _transactions.total_income
  end

  def edit
  end

  def update
    @transaction = Transactions::UpdateService.new(@transaction,
                                                   transaction_params).execute

    if @transaction.updated?
      redirect_to transactions_path
    else
      render :edit
    end
  end

  def destroy
    @transaction = Transactions::DestroyService.new(@transaction).execute

    message = "Transaction deleted successfully" if @transaction.destroyed?

    flash[:danger] = message
    redirect_to transactions_path
  end

  private

  def find_transaction
    @transaction = current_user.transactions.find(params[:id])
  end

  def index_params
    if params[:date].present? && params[:category].present?
      _params = params.require(:date).permit(:year, :month)
      _params.merge(params.permit(:category))
    elsif params[:date].present?
      params.require(:date).permit(:year, :month)
    elsif params[:category].present?
      params.permit(:category)
    end
  end

  def set_transactions
    @transactions = current_user.transactions
  end

  def transaction_params
    params.require(:transaction).permit(:date,
                             :amount,
                             :description,
                             :payment_method_id,
                             :category_id,
                             :kind,
                             :user_id)
  end

  def month_name_label
    if index_params&.dig(:month).present?
      derive_month(index_params.dig(:month))
    else
      current_month
    end
  end

  def year_label
    if index_params&.dig(:year).present?
      derive_year(index_params.dig(:year))
    else
      current_year
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transaction_deletion_message(transaction)
    t('errors.fatal.delete_transaction',
      transaction_amount: number_to_currency(transaction.amount))
  end
end

app/views/transactions/_filter_form.html.haml
= form_tag locals.fetch(:path), method: :get do
  .row
    .no-gutter
      .col-md-6.col-sm-4.col-sm-offset-4.col-md-offset-0= select_month Date::MONTHNAMES.index(@selected_month), {}, class: 'select-control form-control'
      .col-md-3.col-sm-4.col-sm-offset-4.col-md-offset-0= select_year @selected_year, {start_year: Date.today.year, end_year: 5.years.ago.year}, class: 'select-control form-control'
    .col-md-3.col-sm-4.col-sm-offset-4.col-md-offset-0= submit_tag "View", class: "ex-primary-btn form-control"
  -# = link_to "Current", locals.fetch(:path)

app/views/transactions/_form.html.haml
.col-md-4.col-md-offset-4
  = simple_form_for @transaction do |f|
    = f.input :kind, collection: Transaction.kinds.keys.to_a.map, include_blank: false
    = f.input :date, as: :date
    = f.input :description
    = f.input :amount, placeholder: '$00.00'
    - if current_user.categories.blank?
      = f.label "Category"
      = link_to "Add New Category", new_category_path(current_user)
    - else
      = f.association :category,
          collection: current_user.categories,
          selected: (@transaction.category_id || current_user.default_category),
          value_method: :id
    - if current_user.payment_methods.blank?
      = f.label "Payment method"
      = link_to "Add New Payment Method", new_payment_method_path(current_user)
    - else
      = f.association :payment_method,
          collection: current_user.payment_methods,
          selected: (@transaction.payment_method_id || current_user.default_payment_method),
          value_method: :id

    = f.input :create_another, as: :boolean
    = f.button :submit, (f.object.new_record? ? "Save" : "Update"), class: "ex-primary-btn"
    = link_to "Cancel", transactions_path, class: "btn ex-secondary-btn"

app/views/transactions/_transactions.html.haml
= render 'layouts/flashes'
%table.table.table-striped
  %thead
    %th.col-md-1.col-sm-2.col-xs-2 Date
    %th.col-md-4.col-sm-6.col-xs-6 Description
    %th.col-md-2.col-sm-2.col-xs-2 Amount
    %th.col-md-2#category-col Category
    %th.col-md-2#payment-method-col Payment Method
    %th.col-md-1.col-sm-2.col-xs-2 Actions

  %tbody
    - @transactions.each do |transaction|
      %tr
        %td#transaction-date= formatted_date(transaction.date)
        %td#transaction-description= link_to transaction.description, edit_transaction_path(transaction.id)
        %td#transaction-amount.bold.font-size-18{ class: "#{transaction.debit? ? 'debit' : 'credit' }" }= "#{transaction.debit? ? '-' : '+' }" "#{number_to_currency(transaction.amount)}"
        %td#category-col= link_to transaction.category.title, transactions_path(params: {date: {month: params.dig(:date, :month), year: params.dig(:date, :year)}, category: transaction.category.title})
        %td#payment-method-col= transaction.payment_method.name
        %td
          %span.col-md-6= link_to fa_icon("trash-o", class: "fa-2x fa_trash"), transaction, method: :delete, data: {confirm: transaction_deletion_message(transaction)}

app/views/transactions/edit.html.haml
.text-center
  %h1 Update Transaction
= render 'form'

app/views/transactions/index.html.haml
.col-md-10.col-md-offset-1
  .col-md-12.month-list-container

    = render 'shared/transactions_header', locals: {path: transactions_path}

  = render 'transactions'
  .text-center= paginate @transactions

app/views/transactions/new.html.haml
.text-center
  %h1 New Transaction
= render 'form'